# Generated by Django 5.2.5 on 2025-10-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_certificado_arquivos_cliente_apelido_cliente_nuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecertificado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='clientecertificado',
            unique_together={('cliente', 'certificado')},
        ),
    ]
